<div class="editor-outer-wrapper">
    <p class="editor-title">a note from the editor</p>
    <p class="editors-note">
    The Forte Lurex Linen Viscose Jacket in Mother of Pearl features lunar lavishness by night and by day: a blazer in a linen blend shot with lurex for a shimmering surface that shines like a star in the sky.
    </p>
    <p class="editor-footer">By MINNA SHIM, Fashion Editor</p>
</div>
